### ISSUE TITLE
Ability to update or remove plugins

### ISSUE THREAD

**Issue by elcomtik** [cloudalchemy/ansible-grafana#215]
**What is missing?**
Ability to update or remove plugins

**Why do we need it?**
When using grafana plugins, sometimes it needs update to work correctly with latest grafana. Also when we want to uninstall plugin we must do it manually because role doesn't handle it. I would be great if installed plugins reflected list defined by variable _grafana_plugins_. 

**Environment**

* Role version:

    `0.17.0`

* Ansible version information:

    `ansible 2.9.5`

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
Good idea :+1:

We are trying now to refactor this role to use more ansible modules to handle grafana-specific features instead of our hacks. If the upstream `grafana_plugins` module can handle removals of plugins, then it should be a straight forward fix. If it doesn't, please create an issue there as the propagation of features inside modules can take some time.

**Comment by elcomtik** [comment]
Module you mentioned supports update & uninstall according to docs https://docs.ansible.com/ansible/latest/modules/grafana_plugin_module.html. 

Do you want help with refactoring this part of role?

**Comment by paulfantom** [comment]
If you have some spare time, I am open for PRs :)
